import { describe, expect, test } from 'bun:test'
import { createTaktConfig } from '../src/config'
import { generateCSS } from '../src/output/css'
import { generateTailwind } from '../src/output/tailwind'
import { generateTokens } from '../src/output/tokens'
import { generateJSON } from '../src/output/json'
import type { FontMetrics } from '../src/types'

const INTER_METRICS: FontMetrics = {
  unitsPerEm: 2048,
  ascent: 1984,
  descent: -494,
  lineGap: 0,
  capHeight: 1490,
  xHeight: 1118,
  xWidthAvg: 930,
}

const config = createTaktConfig({ font: INTER_METRICS })

describe('generateCSS', () => {
  test('includes header comment', () => {
    const css = generateCSS(config)
    expect(css).toContain('Generated by Takt')
  })

  test('includes --takt-type- variables', () => {
    const css = generateCSS(config)
    expect(css).toContain('--takt-type-base:')
    expect(css).toContain('--takt-type-lg:')
  })

  test('includes --takt-lh- variables', () => {
    const css = generateCSS(config)
    expect(css).toContain('--takt-lh-base:')
  })

  test('includes --takt-space- variables', () => {
    const css = generateCSS(config)
    expect(css).toContain('--takt-space-base:')
    expect(css).toContain('--takt-space-xl:')
  })

  test('includes --takt-rhythm', () => {
    const css = generateCSS(config)
    expect(css).toContain('--takt-rhythm:')
  })
})

describe('generateTailwind', () => {
  test('produces fontSize entries', () => {
    const tw = generateTailwind(config)
    expect(tw.fontSize).toBeDefined()
    expect(tw.fontSize!['base']).toBeDefined()
  })

  test('fontSize entries include lineHeight and letterSpacing', () => {
    const tw = generateTailwind(config)
    const base = tw.fontSize!['base']!
    expect(base).toHaveLength(2)
    expect(base[1]).toHaveProperty('lineHeight')
    expect(base[1]).toHaveProperty('letterSpacing')
  })
})

describe('generateTokens', () => {
  test('produces DTCG structure', () => {
    const tokens = generateTokens(config)
    expect(tokens.typography).toBeDefined()
    expect(tokens.spacing).toBeDefined()
  })
})

describe('generateJSON', () => {
  test('produces valid JSON', () => {
    const json = generateJSON(config)
    expect(() => JSON.parse(json)).not.toThrow()
  })

  test('round-trips the config', () => {
    const json = generateJSON(config)
    const parsed = JSON.parse(json)
    expect(parsed.steps).toHaveLength(config.steps.length)
    expect(parsed.spacing.rhythmUnit).toBe(config.spacing.rhythmUnit)
  })
})
