'use client'
import { CodeBlock } from '@/components/shared/CodeBlock'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import '@/components/shared/code-block.css'
import './docs.css'

const TOC = [
	{ id: 'overview', label: 'Overview' },
	{ id: 'concepts', label: 'Concepts' },
	{ id: 'getting-started', label: 'Getting started' },
	{ id: 'api-create-takt-config', label: 'createTaktConfig' },
	{ id: 'api-normalise-metrics', label: 'normaliseMetrics' },
	{ id: 'api-unpack-font', label: 'unpackFont' },
	{ id: 'api-compute-line-height', label: 'computeLineHeight' },
	{ id: 'api-compute-letter-spacing', label: 'computeLetterSpacing' },
	{ id: 'api-compute-trim', label: 'computeTrim' },
	{ id: 'api-compute-spacing', label: 'computeSpacing' },
	{ id: 'api-generate-scale', label: 'generateScale' },
	{ id: 'output-css', label: 'Output: CSS' },
	{ id: 'output-tailwind', label: 'Output: Tailwind' },
	{ id: 'output-tokens', label: 'Output: Tokens' },
	{ id: 'output-json', label: 'Output: JSON' },
	{ id: 'types-reference', label: 'Types' },
] as const

const INSTALL = `// npm install @takt/core
// or: pnpm add @takt/core / bun add @takt/core`

const QUICK_START = `import { createTaktConfig, generateCSS } from '@takt/core'

const interMetrics = {
  unitsPerEm: 2048,
  ascent: 1984,
  descent: -494,
  lineGap: 0,
  capHeight: 1490,
  xHeight: 1118,
  xWidthAvg: 930,
}

const config = createTaktConfig({
  font: interMetrics,
  baseSize: 16,
  ratio: 1.25,
})

const css = generateCSS(config)
console.log(css)`

const UNPACK_EXAMPLE = `import { unpackFont, createTaktConfig } from '@takt/core'

const metrics = await unpackFont('https://fonts.gstatic.com/s/inter/v20/...')
const config = createTaktConfig({ font: metrics })`

const EXAMPLE_CSS_SNIPPET = `/* Generated by Takt — takt.style */
:root {
  /* Type scale */
  --takt-type-base: clamp(...);
  --takt-lh-base: 1.45;
  --takt-ls-base: -0.01em;
  --takt-space-m: clamp(...);
  --takt-rhythm: 23.2px;
}`

const TAILWIND_CONFIG = `import type { Config } from 'tailwindcss'
import { createTaktConfig, generateTailwind } from '@takt/core'

const config = createTaktConfig({ font: metrics })

export default {
  theme: {
    extend: {
      ...generateTailwind(config),
    },
  },
} satisfies Config`

const TOKENS_SNIPPET = `{
  "typography": {
    "font": {
      "familyName": { "$type": "string", "$value": "Inter" }
    },
    "fontSize": {
      "base": {
        "min": { "$type": "dimension", "$value": "16px" },
        "fluid": { "$type": "dimension", "$value": "clamp(12.24px, ...)" }
      }
    }
  },
  "spacing": {
    "m": {
      "px": { "$type": "dimension", "$value": "18px" },
      "fluid": { "$type": "dimension", "$value": "clamp(15.3px, ...)" }
    }
  }
}`

export function DocsPage() {
	const [activeId, setActiveId] = useState<string>('overview')

	useEffect(() => {
		const nodes = TOC.map(({ id }) => document.getElementById(id)).filter(
			(el): el is HTMLElement => el !== null,
		)
		if (nodes.length === 0) return

		const observer = new IntersectionObserver(
			(entries) => {
				const visible = entries
					.filter((e) => e.isIntersecting && e.target.id)
					.sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top)
				if (visible[0]?.target.id) {
					setActiveId(visible[0].target.id)
				}
			},
			{ rootMargin: '-12% 0px -68% 0px', threshold: [0, 0.1, 0.25] },
		)

		for (const el of nodes) {
			observer.observe(el)
		}
		return () => observer.disconnect()
	}, [])

	return (
		<>
			<div className="docs">
				<div className="docs__layout">
					<div className="docs__toc-wrap">
						<nav className="docs__toc" aria-label="On this page">
							<p className="docs__toc-title">On this page</p>
							<ul className="docs__toc-list">
								{TOC.map(({ id, label }) => (
									<li key={id}>
										<a
											className={`docs__toc-link ${activeId === id ? 'docs__toc-link--active' : ''}`}
											href={`#${id}`}
										>
											{label}
										</a>
									</li>
								))}
							</ul>
						</nav>
					</div>

					<article className="docs__main docs__prose">
						<h1 id="overview">Documentation</h1>
						<p className="docs__lede">
							<code className="docs__inline-code">@takt/core</code> is a type-and-space system
							derived from font metrics. It computes line-height, letter-spacing, a modular type
							scale, rhythm-based spacing, and optional Capsize trimming—then exports CSS variables,
							Tailwind theme fragments, design tokens, or raw JSON. Try it live in the{' '}
							<Link href="/">playground</Link>.
						</p>

						<h2 id="concepts">Concepts</h2>
						<h3>Font metrics</h3>
						<p>
							takt reads the same numbers browsers use: units per em, ascent, descent, cap height,
							x-height, and average character width. From these it derives ratios like{' '}
							<code className="docs__inline-code">xHeightRatio</code> and{' '}
							<code className="docs__inline-code">avgCharWidthRatio</code>. Those ratios describe
							how the face occupies vertical and horizontal space—so spacing decisions can follow
							the font’s shape instead of arbitrary px values.
						</p>

						<h3>Line height</h3>
						<p>
							<code className="docs__inline-code">computeLineHeight</code> maps body-to-display
							sizes to a base leading curve (roughly 1.6 for small text down toward 1.1 for large
							display), then nudges the result using x-height: high x-height faces tend to need
							slightly tighter leading, low x-height slightly looser. The function returns a numeric
							value, a CSS-ready string, and a human-readable{' '}
							<code className="docs__inline-code">reasoning</code> string.
						</p>

						<h3>Letter spacing</h3>
						<p>
							<code className="docs__inline-code">computeLetterSpacing</code> uses size bands: small
							sizes get slight positive tracking; larger display sizes trend negative. Average
							character width scales the result—wider faces need less artificial tracking
							adjustment.
						</p>

						<h3>Spacing and rhythm</h3>
						<p>
							Body line-height and font size define a <strong>rhythm unit</strong>:{' '}
							<code className="docs__inline-code">fontSize × lineHeight</code>. The spacing scale
							(3xs through 5xl) is a set of multipliers on that unit, each with px, rem, and a fluid{' '}
							<code className="docs__inline-code">clamp()</code> between viewport bounds—so vertical
							spacing stays locked to the type rhythm.
						</p>

						<h3>Text trimming</h3>
						<p>
							When <code className="docs__inline-code">trim: true</code>, Capsize-style{' '}
							<code className="docs__inline-code">::before</code> /{' '}
							<code className="docs__inline-code">::after</code> rules reduce extra leading above
							cap height and below the baseline. With{' '}
							<code className="docs__inline-code">textBoxTrim: true</code>, CSS{' '}
							<code className="docs__inline-code">text-box-trim</code> metadata is included for
							engines that support it.
						</p>

						<h2 id="getting-started">Getting started</h2>
						<p>
							Install from npm (or use pnpm, yarn, or bun). The package name is{' '}
							<code className="docs__inline-code">@takt/core</code>.
						</p>
						<CodeBlock code={INSTALL} language="typescript" title="Install" />

						<p>
							Pass resolved <code className="docs__inline-code">FontMetrics</code> into{' '}
							<code className="docs__inline-code">createTaktConfig</code>, then pipe the result into
							any generator.
						</p>
						<CodeBlock code={QUICK_START} language="typescript" title="Quick start" />

						<p>
							To load metrics from a font URL at runtime, use{' '}
							<code className="docs__inline-code">unpackFont</code> (see below) before calling{' '}
							<code className="docs__inline-code">createTaktConfig</code>.
						</p>

						<h2 id="api-create-takt-config">createTaktConfig</h2>
						<div className="docs__signature">
							function createTaktConfig(input: TaktInput): TaktConfig
						</div>
						<p>
							Builds a full <code className="docs__inline-code">TaktConfig</code>: normalised
							metrics, scale steps with line-height, letter-spacing, optional trim, and rhythm-based
							spacing. <code className="docs__inline-code">input.font</code> must be{' '}
							<code className="docs__inline-code">FontMetrics</code> (not a string—use{' '}
							<code className="docs__inline-code">unpackFont</code> first for URLs).
						</p>
						<div className="docs__table-wrap">
							<table>
								<thead>
									<tr>
										<th>Input</th>
										<th>Default</th>
										<th>Notes</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>
											<code className="docs__inline-code">baseSize</code>
										</td>
										<td>16</td>
										<td>Body step size (px)</td>
									</tr>
									<tr>
										<td>
											<code className="docs__inline-code">ratio</code>
										</td>
										<td>1.25</td>
										<td>Modular scale ratio</td>
									</tr>
									<tr>
										<td>
											<code className="docs__inline-code">stepsUp</code> /{' '}
											<code className="docs__inline-code">stepsDown</code>
										</td>
										<td>5 / 2</td>
										<td>Named steps above and below base</td>
									</tr>
									<tr>
										<td>
											<code className="docs__inline-code">viewportMin</code> /{' '}
											<code className="docs__inline-code">viewportMax</code>
										</td>
										<td>320 / 1440</td>
										<td>Fluid clamp range (px)</td>
									</tr>
									<tr>
										<td>
											<code className="docs__inline-code">trim</code> /{' '}
											<code className="docs__inline-code">textBoxTrim</code>
										</td>
										<td>true / false</td>
										<td>Capsize trim and optional text-box trim</td>
									</tr>
								</tbody>
							</table>
						</div>

						<h2 id="api-normalise-metrics">normaliseMetrics</h2>
						<div className="docs__signature">
							function normaliseMetrics(metrics: FontMetrics, familyName?: string):
							NormalisedFontMetrics
						</div>
						<p>
							Adds <code className="docs__inline-code">familyName</code> (default{' '}
							<code className="docs__inline-code">&apos;Unknown&apos;</code>) and ratio fields used
							throughout the pipeline.
						</p>

						<h2 id="api-unpack-font">unpackFont</h2>
						<div className="docs__signature">
							function unpackFont(source: string): Promise&lt;FontMetrics&gt;
						</div>
						<p>
							Loads a font from a URL via{' '}
							<code className="docs__inline-code">@capsizecss/unpack</code> and returns raw{' '}
							<code className="docs__inline-code">FontMetrics</code>. Use in async contexts before{' '}
							<code className="docs__inline-code">createTaktConfig</code>.
						</p>
						<CodeBlock code={UNPACK_EXAMPLE} language="typescript" title="Async font loading" />

						<h2 id="api-compute-line-height">computeLineHeight</h2>
						<div className="docs__signature">
							function computeLineHeight(fontSize: number, metrics: NormalisedFontMetrics): {'{'}{' '}
							value: number; computed: string; reasoning: string {'}'}
						</div>
						<p>
							Computes optimal unitless line-height for a given font size and normalised metrics.
						</p>

						<h2 id="api-compute-letter-spacing">computeLetterSpacing</h2>
						<div className="docs__signature">
							function computeLetterSpacing(fontSize: number, metrics: NormalisedFontMetrics): {'{'}{' '}
							value: number; css: string {'}'}
						</div>
						<p>
							Returns a unitless em value and a CSS string (e.g.{' '}
							<code className="docs__inline-code">-0.02em</code> or{' '}
							<code className="docs__inline-code">0em</code>).
						</p>

						<h2 id="api-compute-trim">computeTrim</h2>
						<div className="docs__signature">
							function computeTrim(fontSize: number, lineHeight: number, metrics: FontMetrics):
							TaktStep[&apos;trim&apos;]
						</div>
						<p>
							Produces Capsize <code className="docs__inline-code">::before</code>/
							<code className="docs__inline-code">::after</code> styles and optional{' '}
							<code className="docs__inline-code">textBox</code> fields for CSS text-box trimming.
						</p>

						<h2 id="api-compute-spacing">computeSpacing</h2>
						<div className="docs__signature">
							function computeSpacing(bodyFontSize: number, bodyLineHeight: number, viewportMin:
							number, viewportMax: number): TaktSpacing
						</div>
						<p>
							Returns <code className="docs__inline-code">rhythmUnit</code> and a named scale
							(3xs–5xl) with px, rem, and fluid clamp strings.
						</p>

						<h2 id="api-generate-scale">generateScale</h2>
						<div className="docs__signature">
							function generateScale(input: ScaleInput): ScaleStep[]
						</div>
						<p>
							Low-level scale generator (used inside{' '}
							<code className="docs__inline-code">createTaktConfig</code>).
							<code className="docs__inline-code">ScaleInput</code> includes{' '}
							<code className="docs__inline-code">baseSize</code>,{' '}
							<code className="docs__inline-code">ratio</code>,{' '}
							<code className="docs__inline-code">stepsUp</code>,{' '}
							<code className="docs__inline-code">stepsDown</code>, and viewport bounds. Each{' '}
							<code className="docs__inline-code">ScaleStep</code> has{' '}
							<code className="docs__inline-code">name</code>,{' '}
							<code className="docs__inline-code">min</code>,{' '}
							<code className="docs__inline-code">max</code>, and a fluid{' '}
							<code className="docs__inline-code">clamp</code> string.
						</p>

						<h2 id="output-css">CSS custom properties</h2>
						<p>
							<code className="docs__inline-code">generateCSS(config)</code> returns a{' '}
							<code className="docs__inline-code">:root</code> block with{' '}
							<code className="docs__inline-code">--takt-type-*</code>,{' '}
							<code className="docs__inline-code">--takt-lh-*</code>,{' '}
							<code className="docs__inline-code">--takt-ls-*</code>,{' '}
							<code className="docs__inline-code">--takt-space-*</code>, and{' '}
							<code className="docs__inline-code">--takt-rhythm</code>.
						</p>
						<CodeBlock code={EXAMPLE_CSS_SNIPPET} language="css" title="Excerpt" />

						<h2 id="output-tailwind">Tailwind</h2>
						<p>
							<code className="docs__inline-code">generateTailwind(config)</code> returns a partial
							theme object:
							<code className="docs__inline-code">fontSize</code> entries as{' '}
							<code className="docs__inline-code">
								[clamp, {'{'} lineHeight, letterSpacing {'}'}]
							</code>
							, plus parallel <code className="docs__inline-code">lineHeight</code>,{' '}
							<code className="docs__inline-code">letterSpacing</code>, and{' '}
							<code className="docs__inline-code">spacing</code> maps. Merge into{' '}
							<code className="docs__inline-code">theme.extend</code>.
						</p>
						<CodeBlock code={TAILWIND_CONFIG} language="typescript" title="tailwind.config.ts" />

						<h2 id="output-tokens">Design tokens (DTCG-style)</h2>
						<p>
							<code className="docs__inline-code">generateTokens(config)</code> nests typography and
							spacing with <code className="docs__inline-code">$type</code> and{' '}
							<code className="docs__inline-code">$value</code> fields for tools that consume
							design-token JSON.
						</p>
						<CodeBlock code={TOKENS_SNIPPET} language="json" title="Shape (abbreviated)" />

						<h2 id="output-json">Raw JSON</h2>
						<p>
							<code className="docs__inline-code">generateJSON(config, pretty?)</code> stringifies
							the full <code className="docs__inline-code">TaktConfig</code> (default{' '}
							<code className="docs__inline-code">pretty: true</code>
							).
						</p>

						<h2 id="types-reference">Types</h2>
						<p>
							Key interfaces exported from <code className="docs__inline-code">@takt/core</code>:
						</p>
						<ul>
							<li>
								<code className="docs__inline-code">FontMetrics</code> — raw font table numbers
							</li>
							<li>
								<code className="docs__inline-code">NormalisedFontMetrics</code> — extends with
								ratios + family name
							</li>
							<li>
								<code className="docs__inline-code">TaktInput</code> — options for{' '}
								<code className="docs__inline-code">createTaktConfig</code>
							</li>
							<li>
								<code className="docs__inline-code">TaktConfig</code> — font, steps, spacing, meta
							</li>
							<li>
								<code className="docs__inline-code">TaktStep</code> — one scale step: fontSize,
								lineHeight, letterSpacing, optional trim
							</li>
							<li>
								<code className="docs__inline-code">TaktSpacing</code> — rhythm unit + named scale
								entries
							</li>
						</ul>

						<p className="docs__footer-note">
							Source and issues:{' '}
							<a href="https://github.com/karlkoch/takt" target="_blank" rel="noopener noreferrer">
								github.com/karlkoch/takt
							</a>
						</p>
					</article>
				</div>
			</div>
		</>
	)
}
