import type { TaktConfig } from '../types'

export function generateCSS(config: TaktConfig): string {
  const lines: string[] = ['/* Generated by Takt — takt.style */', ':root {']

  // Type scale
  lines.push('  /* Type scale */')
  for (const step of config.steps) {
    lines.push(`  --takt-type-${step.name}: ${step.fontSize.clamp};`)
  }
  lines.push('')

  // Line heights
  lines.push('  /* Line heights (per step) */')
  for (const step of config.steps) {
    lines.push(`  --takt-lh-${step.name}: ${step.lineHeight.value};`)
  }
  lines.push('')

  // Letter spacing
  lines.push('  /* Letter spacing (per step) */')
  for (const step of config.steps) {
    lines.push(`  --takt-ls-${step.name}: ${step.letterSpacing.css};`)
  }
  lines.push('')

  // Spacing scale
  lines.push('  /* Spacing scale (rhythm-derived) */')
  for (const [name, value] of Object.entries(config.spacing.scale)) {
    lines.push(`  --takt-space-${name}: ${value.clamp};`)
  }
  lines.push('')

  // Rhythm unit
  lines.push(`  /* Rhythm unit (for custom calculations) */`)
  lines.push(`  --takt-rhythm: ${config.spacing.rhythmUnit}px;`)

  lines.push('}')
  return lines.join('\n')
}
